resources:
  - name: PublicGitHub
    type: GitRepo
    configuration:
      path: Satheesh-Balachandran/Hygieia
      gitProvider: PublicGitHub
      branches:
        include: master
pipelines:
  - name: demo_application
    steps:
      - name: bld_backend
        type: MvnBuild
        configuration:
          sourceLocation: Hygieia
          mvnCommand: clean install -ntp
          configFileLocation: .
          configFileName: mvn-art-config
          inputResources:
            - name: PublicGitHub
          integrations:
            - name: satheeshart
          runtime:
            type: image
            image:
              auto:
                language: java
                versions:
                  - "11"
        execution:
          onStart:
            - javac -version
            - git clone https://github.com/Satheesh-Balachandran/Hygieia.git
            - ls -ltrh
